import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { VitePWA } from 'vite-plugin-pwa'

// Game loop runs on Canvas outside React (see SPEC.md "React / Canvas Boundary").
//
// PWA (Session 21 — ROADMAP.md Finding 0 / A6-A9): manifest + service worker
// are both fully generated by vite-plugin-pwa (generateSW strategy) — nothing
// here hand-writes SW code. registerType 'autoUpdate' + the default
// injectRegister ('auto') mean the plugin injects its own registration
// script into the built index.html; main.jsx is untouched.
export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    VitePWA({
      registerType: 'autoUpdate',
      manifest: {
        name: 'Hunter',
        short_name: 'Hunter',
        description: 'Outmaneuver. Outsmart. Outscore. A browser-based Boids predator game.',
        display: 'standalone',
        // Deliberately 'any', not 'landscape'. The manifest's orientation
        // applies to the WHOLE installed app — start screen, settings,
        // leaderboard, tutorial — not just an in-progress round. Gameplay
        // already locks to landscape imperatively via
        // screen.orientation.lock() in useFullscreen.js, scoped to only
        // while playing. A manifest-level 'landscape' lock would force
        // landscape on every other screen too, which the app deliberately
        // does NOT do today (StartScreen has a portrait-compatible compact
        // layout; RotationToast nudges rather than blocks). See the Session
        // 21 report for the full reasoning — flagged as a judgment call.
        orientation: 'any',
        theme_color: '#0a1628',
        background_color: '#0a1628',
        start_url: '/',
        icons: [
          { src: '/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
          { src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any maskable' },
        ],
      },
      workbox: {
        // index.html is deliberately excluded here (no 'html' extension) —
        // its URL never changes across deploys, so precaching it via the
        // default (effectively cache-first) precache route would strand
        // every installed user on whatever build they first installed, with
        // no recovery short of clearing site data. See the NetworkFirst
        // runtimeCaching entry below, and ROADMAP A8.
        globPatterns: ['**/*.{js,css,ico,png,svg}'],
        // vite-plugin-pwa defaults navigateFallback to 'index.html' for SPA
        // support, which registers its OWN NavigationRoute bound to the
        // precache (via createHandlerBoundToURL) ahead of the custom
        // runtimeCaching entries below — even though index.html isn't
        // precached here, so it would win the route-matching race and defeat
        // the NetworkFirst rule entirely. Explicitly disabled so the
        // NetworkFirst 'navigate' entry below is the only thing handling
        // navigations.
        navigateFallback: null,
        runtimeCaching: [
          {
            // App shell (index.html + any navigation). NetworkFirst: a
            // returning visit always tries the live build first, and only
            // falls back to the last-seen shell when genuinely offline.
            urlPattern: ({ request }) => request.mode === 'navigate',
            handler: 'NetworkFirst',
            options: {
              cacheName: 'hunter-shell',
              networkTimeoutSeconds: 3,
            },
          },
          {
            // Ambient loop + 3 SFX (public/audio/*.mp3, ~184KB total).
            // CacheFirst with rangeRequests explicitly enabled
            // (workbox-range-requests, via the declarative shortcut) — see
            // ROADMAP A9. Chrome's media pipeline can issue byte-range GETs
            // for <audio> even on small files; a cached response served as
            // a plain 200 against a Range request can fail, and the failure
            // mode is silent audio ONLY in the installed app — easy to miss
            // in normal browser-tab testing.
            //
            // Deliberately NOT in the precache globPatterns above: workbox's
            // default precache route doesn't carry the RangeRequestsPlugin,
            // so putting mp3s there would reproduce the exact 206 gotcha
            // this route exists to avoid, and generateSW's declarative
            // config has no way to attach the plugin to that route. This
            // dedicated cache instead warms from real playback — the
            // ambient loop is preloaded on mount by useSound.js, so it
            // caches almost immediately; the one-shot SFX cache on first
            // trigger. That trades a small amount of install-time eagerness
            // for guaranteed-correct playback once cached. Flagged as a
            // judgment call in the Session 21 report.
            urlPattern: ({ url }) => url.pathname.startsWith('/audio/'),
            handler: 'CacheFirst',
            options: {
              cacheName: 'hunter-audio',
              rangeRequests: true,
              cacheableResponse: { statuses: [0, 200] },
            },
          },
          {
            // Leaderboard API — network-only, always. A stale cached board
            // isn't just cosmetic: qualifies() reads entries[entries.length
            // - 1].score as the live 10th-place cutoff, so a stale response
            // can offer submit for a score that no longer ranks, or hide it
            // for one that does (ROADMAP A7).
            urlPattern: ({ url }) => url.pathname.startsWith('/api/'),
            handler: 'NetworkOnly',
          },
        ],
      },
    }),
  ],
  server: {
    proxy: {
      '/api': 'http://localhost:8013', // dev only — same-origin in production
    },
  },
  build: {
    outDir: 'dist',
  },
})
